### ISSUE TITLE
What do you about V2 roadmap?

### ISSUE THREAD

**Issue by simobasso** [sayanee/angularjs-pdf#90]
i'm work on multipage (#55), but this feature change the Api (little more conservative like #71, multiple canvas, autoappend canvas, etc...).

What do you think about plan a roadmap?

for example:

- [ ] svg layer :)
- [ ] more conservative with autogenerated canavs
- [ ] more consevative with isolate scope
- [ ] multiple-page (with multiple canvas)

**Comment by sayanee** [comment]
Sounds all good to me :smile: A couple of things I can think of:

1. Are there any features that can be both V1 and V2 compatible and can be prioritised to work on first? 
- Also which features do we see the API changing for V2? Maybe a feature matrix?

**Comment by nextlevelshit** [comment]
As well it would be nice to have a version of the distributed pdfjs library in the node module dependencies. Sooner I miss the possibility to highlight text like in the pdfjs viewer demo.

[pdfjs-dist node module](https://www.npmjs.com/package/pdfjs-dist)

[pdfjs highlight example](http://mozilla.github.io/pdf.js/web/viewer.html)

PS: I've just stumbled upon your repo. Looks fantastic and saved me a couple of days and brain damage. Soon I will fork your repo and develope a hackable pdf viewer with [electron](http://electron.atom.io/). Maybe you are interested to join? Best wishes from Germany ;-)

**Comment by sayanee** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by sayanee** [comment]
@nextlevelshit checkout [Atom's pdf viewer](https://atom.io/packages/pdf-view) - might help with some code.

**Comment by rnjailamba** [comment]
@nextlevelshit  so basically youre adding support for annotations , right?
Waiting eagerly for it!
Hows the progress going.

**Comment by rnjailamba** [comment]
@sayanee Is anyone working on annotations at the moment.?

**Comment by tusharvikky** [comment]
Any updates on multiple canvas?

**Comment by rhyskoedijk** [comment]
I am very interested in

1. Multiple viewers in the same page (mostly fixed by new version)
2. Select/highlight/copy text from document
3. Annotation layer
4. Responsive UI
